### ISSUE TITLE
Color theming

### ISSUE THREAD

**Issue by luxus1337** [chiel/omni-backup#7]
All colors in one file ass css variables (maybe also usable in javascript). So a color scheme can easaly be applied to the whole CMS.

**Comment by chiel** [comment]
There are colours already, you can reuse them with postcss like so:
```css
@value * as v from '@ocm/core/dist/styles/vars.css';
```

Or just a relative import if you are within the core package.

And then
```css
.thing {
    background: v.c-blue;
}
```

**Comment by chiel** [comment]
My bad, this is actually only in the `media` branch at the moment, but that will be merged soon.
